version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    container_name: nest-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    networks:
      - freecodecamp


  db-test:
    image: postgres:13.0-alpine
    container_name: nest-database-test
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    networks:
      - freecodecamp

networks:
  freecodecamp: